[pytest]
testpaths = tests
addopts = --cov=rdsynth --cov-report=term-missing --cov-report=xml --cov-fail-under=48
filterwarnings =
    ignore::pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\..*
